backend:
  name: github
  repo: csunas/csunas-mind # Path to your Github repository
  branch: master # Branch to update

media_folder: "assets/uploads"

collections:
  - name: "posts" # Used in routes, e.g. /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "event_date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Name of Event", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Event Date", name: "event_date", widget: "datetime"}
      # - {label: "Description", name: "body", widget: "markdown"}
